var myTitle = "Stoh | Simple Text to HTML";
var para1 = "hello world";
var para2 ="alo ma ha";
html{
    head{
        title{&myTitle}
    }
    body{
        nav(color="white" width=3){
            ;hello
        }
        div"nav-bar"{

        }
        div"main"{
            p{&para1}
        }
        footer(id="my-footer"){
            p"footer"{
                ;something
            }
        }
    }
}